# manifests/hello-world-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  containers:
  - name: hello
    image: busybox
    command: ['sh', '-c', 'echo Hello, World! && sleep 30']
  nodeSelector:
    NodeGroupType: default
    NodePool: default
    hub.jupyter.org/node-purpose: user
  tolerations:
  - key: "hub.jupyter.org/dedicated"
    operator: "Equal"
    value: "user"
    effect: "NoSchedule"

