singleuser_image_repo = "dandiarchive/dandihub"
region = "us-west-1"
singleuser_image_tag = "latest"
jupyterhub_domain = "hub-staging.dandiarchive.org"
dandi_api_domain = "https://api.dandiarchive.org"
