name = "eks-hub-staging"
singleuser_image_repo = "dandiarchive/dandihub"
region = "us-west-2"
singleuser_image_tag = "latest"
jupyterhub_domain = "hub-staging.dandiarchive.org"
eks_cluster_version = "1.31"
