name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'images/Dockerfile*'
      - '.github/workflows/docker-build.yaml'
  pull_request:
    paths:
      - 'images/Dockerfile*'
      - '.github/workflows/docker-build.yaml'
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: latest
            dockerfile: Dockerfile
          - tag: latest-openscope
            dockerfile: Dockerfile.openscope
          - tag: latest-allensdk
            dockerfile: Dockerfile.allensdk
          - tag: latest-gpu
            dockerfile: Dockerfile.gpu
          - tag: latest-gpu-allensdk
            dockerfile: Dockerfile.gpu.allensdk
          - tag: latest-matlab
            dockerfile: Dockerfile.matlab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DANDIHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DANDIHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and conditionally push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./images
          file: ./images/${{ matrix.dockerfile }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_DANDIHUB_USERNAME }}/dandihub:${{ matrix.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_DANDIHUB_USERNAME }}/dandihub:${{ matrix.tag }}
          cache-to: type=inline
