name: Generate Data Usage Report

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # TODO param region
        aws-region: us-east-2

    - name: Configure kubectl with AWS EKS
      # TODO param name, region
      run: |
        aws eks update-kubeconfig --name eks-dandihub --region us-east-2

    - name: Sanity check
      run: |
        kubectl get pods -n jupyterhub
